apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: influxdb
  ports:
    - name: influxdb-port
      protocol: TCP
      port: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-container
          image: clbrunet/influxdb
          imagePullPolicy: Never
          ports:
            - name: influxdb-port
              containerPort: 8086
          volumeMounts:
            - name: influxdb-persistent-storage
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
           claimName: influxdb-pvc
