apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
    - name: nginx-https
      protocol: TCP
      port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Never
          image: clbrunet/nginx
          ports:
            - name: nginx-http
              containerPort: 80
            - name: nginx-https
              containerPort: 443
