apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin-http
      protocol: TCP
      port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-container
          imagePullPolicy: Never
          image: clbrunet/phpmyadmin
          ports:
            - name: phpmyadmin-http
              containerPort: 5000
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /root/liveness_probe.sh
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
