apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: wordpress
  ports:
    - name: wordpress-http
      protocol: TCP
      port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress-container
          imagePullPolicy: Never
          image: clbrunet/wordpress
          ports:
            - name: wordpress-http
              containerPort: 5050
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /root/liveness_probe.sh
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
