apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    database: ft_services
    # <bool> enable/disable basic auth
    # basicAuth: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    secureJsonData:
      password: admin
    version: 1
