apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: ftps
  ports:
    - name: ftps-port
      containerPort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps-container
          imagePullPolicy: Never
          image: clbrunet/ftps
          ports:
            - name: ftps-port
              containerPort: 21
